name: Deploy to Server

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          BRANCH=${GITHUB_REF##*/}

          if [ "$BRANCH" == "dev" ]; then
            echo "Deploying Development branch..."
            ssh -o StrictHostKeyChecking=no kruthartha@51.75.18.220 << 'EOF'
              cd ~/Portfolio/portfolio
              git checkout dev
              git pull
              npm install
              pm2 describe dev_app || pm2 start index.js --name dev_app
              pm2 restart dev_app
            EOF
          fi

          if [ "$BRANCH" == "main" ]; then
            echo "Deploying Production branch..."
            ssh -o StrictHostKeyChecking=no kruthartha@51.75.18.220 << 'EOF'
              cd ~/Portfolio/portfolio
              git checkout main
              git pull
              npm install
              pm2 describe prod_app || pm2 start index.js --name prod_app
              pm2 restart prod_app
            EOF
          fi
